name: newjarvis
description: "Chat with AI Assistant"
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  provider: ^6.1.2
  intl: ^0.19.0
  google_sign_in: ^6.2.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  file_picker: ^8.1.7
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  flutter_secure_storage: ^9.2.2
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.5
  google_fonts: ^6.2.1
  scrollable_positioned_list: ^0.3.8

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon_no_circle_blue.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets: 
    - assets/icons/
    - assets/images/
    - assets/icons/book.png
    - assets/icons/menu_write.png
    - assets/icons/claude.png
    - assets/icons/gemini.png
    - assets/icons/gpt.png
    - assets/icons/google.png
    - assets/icons/iconDrive.png
    - assets/icons/iconSlack.png
    - assets/icons/iconConfluence.png
    - assets/icons/assistant.png
    - assets/images/email_marketing.png
    - assets/images/empty_inbox.png
    - assets/images/fire_blue.png
    - assets/icons/iconLocalfile.png
    - assets/icons/iconWeb.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
